global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 1m
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  static_configs:
  - targets:
    - localhost:9090
- job_name: aula
  static_configs:
  - targets:
    -  172.23.38.214:3030
- job_name: servidor
  static_configs:
  - targets:
    -  172.23.38.214:9100
    